#!/bin/bash

DOC=vum.markdown

rm -f -v $DOC
rm -f -v $DOC.html

echo "Adding titles"
echo "% Vim user manual" >> $DOC
echo "% Bram Moolenaar (www.moolenaar.net)" >> $DOC
echo "% 2013 Feb 20" >> $DOC
echo "" >> $DOC

echo "Adding usr_01.markdown"
cat usr_01.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_02.markdown"
cat usr_02.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_03.markdown"
cat usr_03.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_04.markdown"
cat usr_04.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_05.markdown"
cat usr_05.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_06.markdown"
cat usr_06.markdown >> $DOC
echo "" >> $DOC

echo "Converting" $DOC "..."
pandoc $DOC --standalone --smart --output=$DOC.html

echo "Done."
