#!/bin/bash

DOC=vum.markdown

rm -f -v $DOC
rm -f -v $DOC.pdf

echo "Adding titles"
echo "% Vim user manual" >> $DOC
echo "% Bram Moolenaar (www.moolenaar.net)" >> $DOC
echo "% 2013 Feb 20" >> $DOC
echo "" >> $DOC

echo "Adding usr_01.markdown"
cat usr_01.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_02.markdown"
cat usr_02.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_03.markdown"
cat usr_03.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_04.markdown"
cat usr_04.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_05.markdown"
cat usr_05.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_06.markdown"
cat usr_06.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_07.markdown"
cat usr_07.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_08.markdown"
cat usr_08.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_09.markdown"
cat usr_09.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_10.markdown"
cat usr_10.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_11.markdown"
cat usr_11.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_12.markdown"
cat usr_12.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_20.markdown"
cat usr_20.markdown >> $DOC
echo "" >> $DOC

echo "Adding usr_21.markdown"
cat usr_21.markdown >> $DOC
echo "" >> $DOC

echo "Converting" $DOC "..."
pandoc $DOC --standalone --smart \
    --latex-engine=pdflatex --template=ajt.latex \
    -V papersize:a4paper -V fontsize:10pt -V openside:openany \
    -V documentclass:book -V tables -V urlcolor:black \
    -V linkcolor:black -V numbersections -V toc \
    --output=$DOC.pdf

echo "Done."
